set sql_safe_updates = 0;

DROP DATABASE IF EXISTS DBPRODUTO;

CREATE DATABASE DBPRODUTO;

USE DBPRODUTO;

CREATE TABLE PRODUTO (
	IDPRODUTO INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    QUANTIDADE INT NOT NULL,
    PRIMARY KEY(IDPRODUTO)
	
);

CREATE TABLE PROVA (
	IDPROVA INT NOT NULL AUTO_INCREMENT,
	IDPRODUTO INT NOT NULL,
	NOTA FLOAT NOT NULL,
	DATA_PROVA DATE NOT NULL,
	PRIMARY KEY(IDPROVA , IDPRODUTO),
    
	FOREIGN KEY(IDPRODUTO) REFERENCES PRODUTO(IDPRODUTO)
	
);

INSERT INTO
	PRODUTO (IDPRODUTO, NOME, QUANTIDADE)
VALUES
	(1, 'Banana Maça', 2);
INSERT INTO
	PRODUTO (IDPRODUTO, NOME, QUANTIDADE)
VALUES
	(2, 'Pocã', 5);
INSERT INTO
	PRODUTO (IDPRODUTO, NOME, QUANTIDADE)
VALUES
	(3, 'Feijão Carioca', 8);

-- PROVA!!!!!!!!!!!!!!!
INSERT INTO
	PROVA (IDPROVA, IDPRODUTO, NOTA, DATA_PROVA)
VALUES
	(1, 1, 9.50, '2022-05-05');
INSERT INTO
	PROVA (IDPROVA, IDPRODUTO, NOTA, DATA_PROVA)
VALUES
	(2, 2, 9.50, '2022-05-05');
INSERT INTO
	PROVA (IDPROVA, IDPRODUTO, NOTA, DATA_PROVA)
VALUES
	(3, 3, 9.50, '2022-05-05');
    

SELECT * FROM PRODUTO;
