set sql_safe_updates = 0;

DROP DATABASE IF EXISTS DBPRODUTO

CREATE DATABASE DBPRODUTO;

USE DBPRODUTO;

CREATE TABLE PRODUTO (
	IDPRODUTO INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    QUANTIDADE INT NOT NULL,
    PRIMARY KEY(IDPRODUTO)
	
);

INSERT INTO
	PRODUTO (IDPRODUTO, NOME, QUANTIDADE)
VALUES
	(1, 'Banana Maça', 2);
INSERT INTO
	PRODUTO (IDPRODUTO, NOME, QUANTIDADE)
VALUES
	(2, 'Pocã', 5);
INSERT INTO
	PRODUTO (IDPRODUTO, NOME, QUANTIDADE)
VALUES
	(3, 'Feijão Carioca', 8);
SELECT * FROM PRODUTO;
